from typing import Any

class BaseCache:
    async def add(self, key: Any, value: Any) -> None: ...
    async def set(self, key: Any, value: Any) -> None: ...
    async def get(self, key: Any, default: Any | None = None) -> Any: ...

class SimpleMemoryCache(BaseCache): ...
