[project]
name = "palgate"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "annotated-types==0.7.0",
    "certifi==2025.1.31",
    "charset-normalizer==3.4.1",
    "idna==3.10",
    "mypy-extensions==1.0.0",
    "pydantic==2.11.2",
    "pydantic-core==2.33.1",
    "pylgate",
    "python-dotenv==1.0.1",
    "requests==2.32.3",
    "schedule==1.2.2",
    "types-requests==2.32.0.20250328",
    "typing-extensions==4.13.1",
    "typing-inspection==0.4.0",
    "urllib3==2.3.0",
]

[tool.uv.sources]
pylgate = { git = "https://github.com/DonutByte/pylgate.git", rev = "04962e1a40682856226306c26b541750528a8170" }

[dependency-groups]
dev = [
    "mypy>=1.15.0",
]
