from typing import Any


class TelegramClient:
    def __init__(self, session: Any, api_id: int, api_hash: str) -> None: ...
    async def connect(self) -> None: ...
    async def disconnect(self) -> None: ...
    async def is_user_authorized(self) -> bool: ...
    async def start(self, phone: Any = ...) -> Any: ...
    def __call__(self, request: Any) -> Any: ...
