name: Python CI with Docker

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  integration:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v5
    
    - name: Sync uv
      run: make install

    - name: Install protoc
      uses: arduino/setup-protoc@v3

    - name: Compile proto
      run: make proto

    - name: Run mypy
      run: make mypy

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: |
        docker build -t palgate-tg-notify .

    - name: Push Docker image to Server
      run: |
        mkdir ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

        ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} <<EOF
          docker stop palgate-tg-notify-container || true
          docker rm -f palgate-tg-notify-container || true
          docker rmi -f palgate-tg-notify:latest || true
        EOF
        docker save palgate-tg-notify | ssh -o StrictHostKeyChecking=no -C ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} docker load
        ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} <<EOF
          docker run --env-file ${{ secrets.ENV_FILE_PATH }} -d --name palgate-tg-notify-container palgate-tg-notify:latest
        EOF
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
